-- SQLite
-- SELECT * FROM RECORD_PITCHER WHERE (CAST(P_IP as INTEGER) >= 144) ORDER BY P_ERA;

-- DELETE FROM BOARD_BOARD WHERE brd_no = 6;
-- DELETE FROM BOARD_BOARD WHERE brd_no = 7;
-- DELETE FROM BOARD_BOARD WHERE brd_no = 11;
-- DELETE FROM BOARD_BOARD WHERE brd_no = 12;
-- DELETE FROM BOARD_BOARD WHERE brd_no = 13;
-- DELETE FROM BOARD_BOARD WHERE brd_no = 14;

-- DELETE FROM RECORD_RECORD WHERE rcd_no BETWEEN 516 AND 540;