# Generated by Django 2.2.5 on 2019-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rcd_awaypoint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rcd_homepoint',
            field=models.IntegerField(null=True),
        ),
    ]
