# Generated by Django 2.2.5 on 2019-12-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20191210_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
