# Generated by Django 2.2.5 on 2019-12-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
