# Generated by Django 2.2.5 on 2019-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0005_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rcd_no', models.AutoField(primary_key=True, serialize=False)),
                ('rcd_date', models.CharField(max_length=100)),
                ('rcd_gujang', models.CharField(max_length=50)),
                ('rcd_awayteam', models.CharField(max_length=50)),
                ('rcd_awaypoint', models.IntegerField(null=True)),
                ('rcd_homepoint', models.IntegerField(null=True)),
                ('rcd_hometeam', models.CharField(max_length=50)),
                ('rcd_awayresult', models.CharField(max_length=50)),
                ('rcd_homeresult', models.CharField(max_length=50)),
                ('rcd_etc', models.CharField(max_length=100)),
            ],
        ),
    ]
