# Generated by Django 2.2.5 on 2019-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rcd_awaypoint',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='rcd_homepoint',
            field=models.CharField(max_length=20),
        ),
    ]
