# Generated by Django 2.2.5 on 2019-12-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20191211_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
