# Generated by Django 2.2.5 on 2019-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_pitcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('t_index', models.AutoField(primary_key=True, serialize=False)),
                ('t_no', models.IntegerField()),
                ('t_name', models.CharField(max_length=30)),
                ('t_game', models.IntegerField()),
                ('t_win', models.IntegerField()),
                ('t_lose', models.IntegerField()),
                ('t_draw', models.IntegerField()),
                ('t_per', models.FloatField()),
                ('t_chai', models.IntegerField()),
                ('t_10', models.CharField(max_length=30)),
                ('t_cont', models.CharField(max_length=30)),
                ('t_home', models.CharField(max_length=30)),
                ('t_away', models.CharField(max_length=30)),
            ],
        ),
    ]
