# Generated by Django 2.2.5 on 2019-12-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
