# Generated by Django 2.2.5 on 2019-12-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
