# Generated by Django 2.2.5 on 2019-12-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_auto_20191213_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hitter',
        ),
    ]
