# Generated by Django 2.2.5 on 2019-12-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0022_hitter_pitcher_record_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pitcher',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
