# Generated by Django 2.2.5 on 2019-12-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0024_pitcher_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hitter',
        ),
        migrations.DeleteModel(
            name='Pitcher',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
