# Generated by Django 2.2.5 on 2019-12-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0026_hitter_pitcher_record_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
