# Generated by Django 2.2.5 on 2019-12-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0032_pitcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
