# Generated by Django 2.2.5 on 2019-12-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0036_pitcher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pitcher',
        ),
    ]
