# Generated by Django 2.2.5 on 2019-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('brd_no', models.AutoField(primary_key=True, serialize=False)),
                ('brd_title', models.CharField(max_length=150)),
                ('brd_content', models.TextField()),
                ('brd_writer', models.CharField(max_length=20)),
                ('brd_hit', models.IntegerField()),
                ('brd_date', models.DateTimeField(auto_now_add=True)),
                ('brd_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
